/*
 * API сервиса prepaid карты для Партнёра
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sZZZ;

import io.restassured.response.Response;

import java.util.function.Function;

public interface Oper {

    <T> T execute(Function<Response, T> handler);

}
