/*
 * Сервис аутентификации пользователей
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package s1111.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Ответ на получение пользователя
 */
@ApiModel(description = "Ответ на получение пользователя")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-15T21:07:57.053023600+03:00[Europe/Moscow]")
public class FindUserResponse {
    public static final String SERIALIZED_NAME_USER = "user";
    @SerializedName(SERIALIZED_NAME_USER)
    private User user;

    public static final String SERIALIZED_NAME_DEVICE = "device";
    @SerializedName(SERIALIZED_NAME_DEVICE)
    private UserDevice device;


    public FindUserResponse user(User user) {

        this.user = user;
        return this;
    }

    /**
     * Get user
     * @return user
     **/
    @ApiModelProperty(required = true, value = "")

    public User getUser() {
        return user;
    }


    public void setUser(User user) {
        this.user = user;
    }


    public FindUserResponse device(UserDevice device) {

        this.device = device;
        return this;
    }

    /**
     * Get device
     * @return device
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public UserDevice getDevice() {
        return device;
    }


    public void setDevice(UserDevice device) {
        this.device = device;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FindUserResponse findUserResponse = (FindUserResponse) o;
        return Objects.equals(this.user, findUserResponse.user) &&
                Objects.equals(this.device, findUserResponse.device);
    }

    @Override
    public int hashCode() {
        return Objects.hash(user, device);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FindUserResponse {\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("    device: ").append(toIndentedString(device)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

