/*
 * Сервис аутентификации пользователей
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package s1111.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Arrays;
import java.util.Objects;

/**
 * Информация об устройстве
 */
@ApiModel(description = "Информация об устройстве")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-15T21:07:57.053023600+03:00[Europe/Moscow]")
public class UserDevice {
  public static final String SERIALIZED_NAME_DEVICE_ID = "deviceId";
  @SerializedName(SERIALIZED_NAME_DEVICE_ID)
  private String deviceId;

  public static final String SERIALIZED_NAME_OS_VERSION = "osVersion";
  @SerializedName(SERIALIZED_NAME_OS_VERSION)
  private String osVersion;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private UserDeviceStatus status;

  public static final String SERIALIZED_NAME_PUBLIC_KEY = "publicKey";
  @SerializedName(SERIALIZED_NAME_PUBLIC_KEY)
  private byte[] publicKey;


  public UserDevice deviceId(String deviceId) {
    
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Uuid объекта
   * @return deviceId
  **/
  @ApiModelProperty(example = "b657e944-397b-445a-993d-40e8cd2262b2", required = true, value = "Uuid объекта")

  public String getDeviceId() {
    return deviceId;
  }


  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  public UserDevice osVersion(String osVersion) {
    
    this.osVersion = osVersion;
    return this;
  }

   /**
   * OS Version
   * @return osVersion
  **/
  @ApiModelProperty(required = true, value = "OS Version")

  public String getOsVersion() {
    return osVersion;
  }


  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }


  public UserDevice status(UserDeviceStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserDeviceStatus getStatus() {
    return status;
  }


  public void setStatus(UserDeviceStatus status) {
    this.status = status;
  }


  public UserDevice publicKey(byte[] publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Публичный ключ устройства (RSA 2048 бит, Base64)
   * @return publicKey
  **/
  @ApiModelProperty(required = true, value = "Публичный ключ устройства (RSA 2048 бит, Base64)")

  public byte[] getPublicKey() {
    return publicKey;
  }


  public void setPublicKey(byte[] publicKey) {
    this.publicKey = publicKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDevice userDevice = (UserDevice) o;
    return Objects.equals(this.deviceId, userDevice.deviceId) &&
        Objects.equals(this.osVersion, userDevice.osVersion) &&
        Objects.equals(this.status, userDevice.status) &&
        Arrays.equals(this.publicKey, userDevice.publicKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, osVersion, status, Arrays.hashCode(publicKey));
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDevice {\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

