/*
 * Сервис аутентификации пользователей
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package s1111.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Информация о пользователе
 */

public class User {
  public static final String SERIALIZED_NAME_PARTNER_UUID = "partnerUuid";
  private String partnerUuid;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  private String uuid;

  public static final String SERIALIZED_NAME_PHONE = "phone";

  private String phone;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private UserStatus status;

  public static final String SERIALIZED_NAME_UNC = "unc";
  @SerializedName(SERIALIZED_NAME_UNC)
  private String unc;

  public static final String SERIALIZED_NAME_MDM_ID = "mdmId";
  @SerializedName(SERIALIZED_NAME_MDM_ID)
  private String mdmId;

  public static final String SERIALIZED_NAME_OFFER_ACCEPTED = "offerAccepted";
  @SerializedName(SERIALIZED_NAME_OFFER_ACCEPTED)
  private Boolean offerAccepted = true;

  public static final String SERIALIZED_NAME_CARD_PUBLIC_ID = "cardPublicId";
  @SerializedName(SERIALIZED_NAME_CARD_PUBLIC_ID)
  private String cardPublicId;

  public static final String SERIALIZED_NAME_PARTNER_NAME = "partnerName";
  @SerializedName(SERIALIZED_NAME_PARTNER_NAME)
  private String partnerName;


  public User partnerUuid(String partnerUuid) {

    this.partnerUuid = partnerUuid;
    return this;
  }

  /**
   * Uuid объекта
   * @return partnerUuid
   **/
  @ApiModelProperty(example = "b657e944-397b-445a-993d-40e8cd2262b2", required = true, value = "Uuid объекта")

  public String getPartnerUuid() {
    return partnerUuid;
  }


  public void setPartnerUuid(String partnerUuid) {
    this.partnerUuid = partnerUuid;
  }


  public User uuid(String uuid) {

    this.uuid = uuid;
    return this;
  }

  /**
   * Uuid объекта
   * @return uuid
   **/
  @ApiModelProperty(example = "b657e944-397b-445a-993d-40e8cd2262b2", required = true, value = "Uuid объекта")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public User phone(String phone) {

    this.phone = phone;
    return this;
  }

  /**
   * Номер телефона пользователя
   * @return phone
   **/
  @ApiModelProperty(example = "79031234567", required = true, value = "Номер телефона пользователя")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    this.phone = phone;
  }


  public User status(UserStatus status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @ApiModelProperty(required = true, value = "")

  public UserStatus getStatus() {
    return status;
  }


  public void setStatus(UserStatus status) {
    this.status = status;
  }


  public User unc(String unc) {

    this.unc = unc;
    return this;
  }

  /**
   * Уникальный идентификатор клиента
   * @return unc
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Уникальный идентификатор клиента")

  public String getUnc() {
    return unc;
  }


  public void setUnc(String unc) {
    this.unc = unc;
  }


  public User mdmId(String mdmId) {

    this.mdmId = mdmId;
    return this;
  }

  /**
   * MDM-ID клиента
   * @return mdmId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MDM-ID клиента")

  public String getMdmId() {
    return mdmId;
  }


  public void setMdmId(String mdmId) {
    this.mdmId = mdmId;
  }


  public User offerAccepted(Boolean offerAccepted) {

    this.offerAccepted = offerAccepted;
    return this;
  }

  /**
   * Признак \&quot;Оферта принята\&quot;
   * @return offerAccepted
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Признак \"Оферта принята\"")

  public Boolean getOfferAccepted() {
    return offerAccepted;
  }


  public void setOfferAccepted(Boolean offerAccepted) {
    this.offerAccepted = offerAccepted;
  }


  public User cardPublicId(String cardPublicId) {

    this.cardPublicId = cardPublicId;
    return this;
  }

  /**
   * Публичный идентификатор продукта (карты)
   * @return cardPublicId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Публичный идентификатор продукта (карты)")

  public String getCardPublicId() {
    return cardPublicId;
  }


  public void setCardPublicId(String cardPublicId) {
    this.cardPublicId = cardPublicId;
  }


  public User partnerName(String partnerName) {

    this.partnerName = partnerName;
    return this;
  }

  /**
   * Наименование партнера
   * @return partnerName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "XXX", value = "Наименование партнера")

  public String getPartnerName() {
    return partnerName;
  }


  public void setPartnerName(String partnerName) {
    this.partnerName = partnerName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.partnerUuid, user.partnerUuid) &&
            Objects.equals(this.uuid, user.uuid) &&
            Objects.equals(this.phone, user.phone) &&
            Objects.equals(this.status, user.status) &&
            Objects.equals(this.unc, user.unc) &&
            Objects.equals(this.mdmId, user.mdmId) &&
            Objects.equals(this.offerAccepted, user.offerAccepted) &&
            Objects.equals(this.cardPublicId, user.cardPublicId) &&
            Objects.equals(this.partnerName, user.partnerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partnerUuid, uuid, phone, status, unc, mdmId, offerAccepted, cardPublicId, partnerName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    sb.append("    partnerUuid: ").append(toIndentedString(partnerUuid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    unc: ").append(toIndentedString(unc)).append("\n");
    sb.append("    mdmId: ").append(toIndentedString(mdmId)).append("\n");
    sb.append("    offerAccepted: ").append(toIndentedString(offerAccepted)).append("\n");
    sb.append("    cardPublicId: ").append(toIndentedString(cardPublicId)).append("\n");
    sb.append("    partnerName: ").append(toIndentedString(partnerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

