/*
 * Сервис аутентификации пользователей
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package s1111.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Статус устройства пользователя
 */
@JsonAdapter(UserDeviceStatus.Adapter.class)
public enum UserDeviceStatus {
  
  ACTIVE("ACTIVE"),
  
  BLOCKED("BLOCKED"),
  
  DELETED("DELETED");

  private String value;

  UserDeviceStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserDeviceStatus fromValue(String value) {
    for (UserDeviceStatus b : UserDeviceStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<UserDeviceStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserDeviceStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public UserDeviceStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return UserDeviceStatus.fromValue(value);
    }
  }
}

